package com.willfp.talismans.display;

import com.willfp.eco.core.display.DisplayModule;
import com.willfp.eco.core.display.DisplayPriority;
import com.willfp.eco.core.placeholder.context.PlaceholderContext;
import com.willfp.eco.core.placeholder.context.PlaceholderContextExtensions;
import com.willfp.eco.libs.kotlin.Metadata;
import com.willfp.eco.libs.kotlin.collections.CollectionsKt;
import com.willfp.eco.libs.kotlin.jvm.internal.Intrinsics;
import com.willfp.eco.libs.kotlin.jvm.internal.SourceDebugExtension;
import com.willfp.eco.util.StringUtilsExtensions;
import com.willfp.libreforge.ItemProvidedHolder;
import com.willfp.talismans.TalismansPluginKt;
import com.willfp.talismans.talismans.Talisman;
import com.willfp.talismans.talismans.util.TalismanChecks;
import com.willfp.talismans.talismans.util.TalismanUtils;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

// $VF: Compiled from TalismanDisplay.kt
@Metadata(
   mv = {2, 3, 0},
   k = 1,
   xi = 48,
   d1 = "\u0000*\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0011\n\u0002\u0010\u0000\n\u0002\b\u0002\bÆ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003J3\u0010\u0004\u001a\u00020\u00052\u0006\u0010\u0006\u001a\u00020\u00072\b\u0010\b\u001a\u0004\u0018\u00010\t2\u0012\u0010\n\u001a\n\u0012\u0006\b\u0001\u0012\u00020\f0\u000b\"\u00020\fH\u0016¢\u0006\u0002\u0010\r¨\u0006\u000e",
   d2 = {
         "Lcom/willfp/talismans/display/TalismanDisplay;",
         "Lcom/willfp/eco/core/display/DisplayModule;",
         "<init>",
         "()V",
         "display",
         "",
         "itemStack",
         "Lorg/bukkit/inventory/ItemStack;",
         "player",
         "Lorg/bukkit/entity/Player;",
         "args",
         "",
         "",
         "(Lorg/bukkit/inventory/ItemStack;Lorg/bukkit/entity/Player;[Ljava/lang/Object;)V",
         "core-plugin"
   }
)
@SourceDebugExtension(
   "SMAP\nTalismanDisplay.kt\nKotlin\n*S Kotlin\n*F\n+ 1 TalismanDisplay.kt\ncom/willfp/talismans/display/TalismanDisplay\n+ 2 _Collections.kt\nkotlin/collections/CollectionsKt___CollectionsKt\n*L\n1#1,64:1\n1586#2:65\n1661#2,3:66\n1586#2:69\n1661#2,3:70\n*S KotlinDebug\n*F\n+ 1 TalismanDisplay.kt\ncom/willfp/talismans/display/TalismanDisplay\n*L\n46#1:65\n46#1:66,3\n53#1:69\n53#1:70,3\n*E\n"
)
public final class TalismanDisplay extends DisplayModule {
   @NotNull
   public static final TalismanDisplay INSTANCE = new TalismanDisplay();

   private TalismanDisplay() {
      super(TalismansPluginKt.getPlugin(), DisplayPriority.LOWEST);
   }

   public void display(@NotNull ItemStack itemStack, @Nullable Player player, @NotNull Object... args) {
      Intrinsics.checkNotNullParameter(itemStack, "itemStack");
      Intrinsics.checkNotNullParameter(args, "args");
      TalismanUtils var10000 = TalismanUtils.INSTANCE;
      Material var10001 = itemStack.getType();
      Intrinsics.checkNotNullExpressionValue(var10001, "getType(...)");
      if (var10000.isTalismanMaterial(var10001)) {
         ItemMeta var32 = itemStack.getItemMeta();
         if (var32 != null) {
            ItemMeta meta = var32;
            List var33 = meta.getLore();
            if (var33 == null) {
               var33 = new ArrayList();
            }

            List itemLore = new ArrayList(var33);
            // eco can render the same ItemStack more than once (for example in the
            // admin GUI). Lines prefixed with §z are generated by this display, so
            // remove the previous render before rebuilding the lore.
            itemLore.removeIf(line -> line instanceof String && ((String)line).startsWith("§z"));
            Talisman var34 = TalismanChecks.getTalismanOnItem(itemStack);
            if (var34 != null) {
               Talisman talisman = var34;
               PlaceholderContext placeholderContext = PlaceholderContextExtensions.placeholderContext(player, itemStack);
               meta.setDisplayName(StringUtilsExtensions.formatEco(talisman.getName(), placeholderContext));
               ItemMeta var35 = talisman.getItemStack().getItemMeta();
               if (var35 != null ? var35.hasCustomModelData() : false) {
                  ItemMeta var36 = talisman.getItemStack().getItemMeta();
                  meta.setCustomModelData(var36 != null ? var36.getCustomModelData() : null);
               }

               List lore = new ArrayList();
               Iterable provided = talisman.getDescription();
               List var20 = lore;
               int $i$f$map = 0;
               Iterable $this$map$iv = provided;
               var destination$iv$iv = new ArrayList(CollectionsKt.collectionSizeOrDefault(provided, 10));
               int $i$f$mapTo = 0;

               for (Object item$iv$iv : $this$map$iv) {
                  String it = (String)item$iv$iv;
                  Collection var21 = destination$iv$iv;
                  int var17/* $VF was: $i$a$-map-TalismanDisplay$display$1 */ = 0;
                  Intrinsics.checkNotNull(it);
                  var21.add("§z" + StringUtilsExtensions.formatEco(it, placeholderContext));
               }

               var20.addAll((Collection & List)destination$iv$iv);
               lore.addAll(itemLore);
               if (player != null) {
                  ItemProvidedHolder providedx = new ItemProvidedHolder(talisman, itemStack);
                  $this$map$iv = providedx.getNotMetLines(player);
                  int $i$f$mapx = 0;
                  Iterable var26 = $this$map$iv;
                  var destination$iv$ivx = new ArrayList(CollectionsKt.collectionSizeOrDefault($this$map$iv, 10));
                  int $i$f$mapTox = 0;

                  for (Object item$iv$iv : var26) {
                     String it = (String)item$iv$iv;
                     Collection var31 = destination$iv$ivx;
                     int var19/* $VF was: $i$a$-map-TalismanDisplay$display$lines$1 */ = 0;
                     var31.add("§z" + it);
                  }

                  List lines = (List)destination$iv$ivx;
                  if (!lines.isEmpty()) {
                     lore.add("§z");
                     lore.addAll(lines);
                  }
               }

               meta.setLore(lore);
               itemStack.setItemMeta(meta);
            }
         }
      }
   }
}
